In [2]:
import numpy as np

In [2]:
myList = [1,2,3]

In [3]:
myList

[1, 2, 3]

In [4]:
type(myList)

list

In [6]:
myArray = np.array(myList)

In [8]:
myArray

array([1, 2, 3])

In [9]:
type(myArray)

numpy.ndarray

In [3]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [4]:
np.zeros(shape=(5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
type(0)

int

In [6]:
type(0.)

float

In [7]:
#dấu chấm phía sau số 1 - là tất cả các số dấu phẩy động.
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
## this is the function to initialization random data
# put the random seed (hạt giống ngẫu nhiên)
#cho phép tạo ra các số ngẫu nhiên giống nhau mỗi lần.
np.random.seed(101)
#lấy từ 0 đến 100 cho ra 10 số ngẫu nhiên 
arr = np.random.randint(0,100,10)

In [12]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [13]:
arr2= np.random.randint(0,100,10)

In [14]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [19]:
#Max, Min, Mean of array
arr.max()

95

In [25]:
# Find the position of the maximum value
arr.argmax()

0

In [24]:
arr.argmax()

0

In [26]:
arr.min()

9

In [27]:
#Find the position of the min value
arr.argmin()

7

In [28]:
arr.mean()

60.8

In [30]:
#it is a vector
arr.shape

(10,)

In [32]:
#we want to change the shape > fomart as below:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

=============

In [41]:
#Lastly we want to understand indexing.
#include 2 steps as above (List array and reshape it)
mat = np.arange(0,100).reshape(10,10)

In [43]:
#check the shape of mat variable
mat.shape

(10, 10)

In [44]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
# I would like to coatch row0 and column1 
row = 0
col =1

In [46]:
mat[row,col]

1

In [47]:
mat[0,1]

1

In [48]:
mat[5,6]

56

In [49]:
#catch the position the colum
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
mat[:,0].shape

(10,)

In [57]:
mat[:,0].reshape(10,1)

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [59]:
#or catch the position the row
mat[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
mat[1,:].shape

(10,)

In [64]:
mat[1,:].reshape(10,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [65]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
#if you want to catch the matrix (3,3)
mat[0:3,0:4] =0

In [70]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
#copy the new mat
Newmat= mat.copy()

In [72]:
Newmat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [74]:
Newmat[0:6, :] =10

In [75]:
Newmat

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])